version: 0.2
       
phases:
  install:
    commands:
      - echo "Installing Hugo..."
      - cd ~
      - wget https://github.com/gohugoio/hugo/releases/download/v0.71.0/hugo_0.71.0_Linux-64bit.deb
      - dpkg -i hugo*.deb
  build:
    commands:
      - hugo
      - echo "S3 Upload Beginning"
      - aws s3 sync public/ s3://moneer-web-cicd/ --region us-east-1 --delete --acl public-read
      - echo "S3 Upload Complete"
  post_build:
    commands:
      - echo "Build complete"
